//! Generates `MIGRATIONS` from the `migrations/` directory at build time, so
//! the directory is the single source of truth: adding a migration only means
//! dropping a new `NUM-NAME.sql` file into `migrations/` and rebuilding.
//!
//! Ordering is decided by the parsed leading number, not by the file name, so
//! zero-padding is optional (`1-init.sql` and `10-ten.sql` sort numerically).
//! Files that do not follow the pattern are ignored; duplicate numbers abort
//! the build.
//!
//! Also materializes a placeholder `ui/dist/index.html` when the real UI has
//! not been built yet (`pnpm build`), because build outputs are not tracked in
//! git while rust-embed aborts compilation when the folder is missing.

use std::env;
use std::fs;
use std::path::Path;

/// Served when the embeddable UI has not been built; `pnpm build` at the repo
/// root replaces it with the real Vue app (vite empties the directory first).
const UI_PLACEHOLDER: &str = r#"<!doctype html>
<html lang="zh">
  <head>
    <meta charset="utf-8" />
    <title>agent-memory</title>
  </head>
  <body style="font-family: system-ui, sans-serif; margin: 4rem; color: #555">
    <h1>管理界面尚未构建</h1>
    <p>
      当前嵌入的是占位页。在仓库根目录执行 <code>pnpm install &amp;&amp; pnpm build</code>
      生成 ui/dist，再重新 <code>cargo build</code> 即可嵌入完整界面。
    </p>
  </body>
</html>
"#;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by Cargo");
    let migrations_dir = Path::new(&manifest_dir).join("migrations");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by Cargo");

    ensure_ui_placeholder(Path::new(&manifest_dir));

    let mut ordered: Vec<(usize, String)> = Vec::new();
    for entry in fs::read_dir(&migrations_dir).expect("failed to read the migrations directory") {
        let entry = entry.expect("failed to read a migrations directory entry");
        let file_name = entry.file_name();
        let name = file_name
            .to_str()
            .expect("migration file names must be valid UTF-8");
        if let Some(number) = migration_number(name) {
            ordered.push((number, name.to_owned()));
        }
    }
    ordered.sort_by_key(|(number, _)| *number);
    for window in ordered.windows(2) {
        if window[0].0 == window[1].0 {
            panic!(
                "duplicate migration number {} in `migrations/`",
                window[0].0
            );
        }
    }

    let entries = ordered
        .iter()
        .map(|(_, name)| {
            format!(
                "    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/migrations/\", {name:?})),"
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let generated = format!(
        "// Generated by build.rs from the `migrations/` directory; do not edit.\n\
         pub(crate) const MIGRATIONS: &[&str] = &[\n{entries}\n];\n"
    );
    fs::write(Path::new(&out_dir).join("migrations.rs"), generated)
        .expect("failed to write the generated migrations module");

    println!("cargo:rerun-if-changed=migrations");
    // 目录级跟踪：pnpm build 重写 ui/dist 后，下次 cargo build 会重跑本脚本并
    // 重编译（rust-embed 随之重新嵌入），无需 cargo clean。
    println!("cargo:rerun-if-changed=ui/dist");
}

/// rust-embed embeds `ui/dist` at compile time and aborts the build when the
/// folder is absent; since build outputs stay out of version control, a fresh
/// clone needs this stub to remain compilable.
fn ensure_ui_placeholder(manifest_dir: &Path) {
    let dist = manifest_dir.join("ui").join("dist");
    let index = dist.join("index.html");
    if !index.exists() {
        fs::create_dir_all(&dist).expect("failed to create ui/dist");
        fs::write(&index, UI_PLACEHOLDER).expect("failed to write the ui/dist placeholder");
    }
}

/// Returns the leading migration number of a `NUM-NAME.sql` file name.
fn migration_number(name: &str) -> Option<usize> {
    if !name.ends_with(".sql") {
        return None;
    }
    let (prefix, _) = name.split_once('-')?;
    prefix.parse::<usize>().ok()
}
